---
title: "PhantomPurgeR: Vignette"
author: "Rick Farouni"
package: PhantomPurgeR
date: "`r Sys.Date()`"
output: BiocStyle::html_document
vignette: >
  %\VignetteIndexEntry{Converting BUS format into sparse matrix}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


```{r, echo=FALSE, results="hide", message=FALSE}
require(knitr)
opts_chunk$set(error=FALSE, message=FALSE, warning=FALSE)
```
```{r}
library(PhantomPurgeR)
```


# Simulate Data 
```{r eval=FALSE, include=TRUE}
input_dir <-  tempdir()
tempfile_prefix <-file.path(input_dir, "sample")
samples <-
  DropletUtils:::sim10xMolInfo(tempfile_prefix, 
                               nsamples = 4, 
                               umi.length = 10,
                               barcode.length = 8,
                               ngenes = 200,
                               nmolecules = 1000000,
                               swap.frac = 0.1,
                               ave.read = 20, 
                               version = c("3"))
```


### Read filepaths of all h5 files found in input_dir


```{r}
input_dir <- system.file("extdata", package = "PhantomPurgeR")
```


```{r}
samples <- get_h5_filenames(input_dir)
samples
```

Change the names of the samples

```{r}
names(samples) <- paste0("s", 1:4)
samples
```

# Run PhantomPurgeR workflow

## (1) Read data

```{r}
out <- read10xMolInfoSamples(samples, barcode_length = NULL)
```

##  (2) Join and merge data

```{r}
out <- join_data(out)
```

## (3) Estimate sample index hopping rate

```{r}
out <- estimate_hopping_rate(out, max_r = NULL)
```

## (4) Purge phantom molecules

```{r}
out <- purge_phantoms(out,
                      torc=3,
                      return_readcounts=FALSE,
                      return_discarded=TRUE)
out 
```

Alternatively all the preceding 4 steps can all be run at once.

```{r}
#out <- phantom_purger(samples, torc=3, max_r = NULL, barcode_length=NULL, return_readcounts=FALSE, return_discarded=TRUE)
```

### Make plots

```{r}
dataset_name <- "test400"
```
```{r message=FALSE, warning=FALSE}
plots <- make_plots(out, dataset_name, x_lim = 50, legend_rel_width=0.2)
```


```{r message=FALSE, warning=FALSE}
plots 
```

```{r}
sessionInfo()
```


